_base_: ../../base.yaml

model:
  type: vae
  latent_dim: 128
  image_size: 64
  channels: 3
  beta: 1.0  # Standard VAE

training:
  epochs: 300
  batch_size: 128
  device: cuda

optimizer:
  type: adam
  lr: 0.001
  betas: [0.9, 0.999]